spring:
  application:
    name: sb07_HRBank_team01

#  h2:
#    console:
#      enabled: true # 콘솔 실행
#      path: /h2-console #default 접속주소 localhost:8080/h2-console
#
#  datasource:
#    url: jdbc:h2:~/hrbank;MODE=PostgreSQL
#    username: sa # default
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank_user
    password: hrbank1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  open-in-view: false

HRBank:
  storage:
    type: local
    local:
      # path: Users/사용자이름/Desktop/HRBank/
      root-path: "${user.home}/Desktop/HRBank/"